### ISSUE TITLE
GROS BUG CRITIQUE, LA SECURIT2 EST EN JEU

### ISSUE THREAD

**Issue by CharrierTim** [H3Aether/Personal-Website#1]
Bonjour,

ENCORE une fois, votre site comporte un bogue impardonnable. je trouve cela inadmissible. QUAND je souhaite accéder au lien du code GitHub de votre article au lien suivant : https://alexisboussaroque.me/articles/creating_a_rest_api/article.html , bah erreur !

**Comment by H3Aether** [comment]
C'est corrigé bouffon

**Comment by CharrierTim** [comment]
super merci d'avoir pris en compte ma demande, résolution rapide, je recommande 5/5
